services:
  - type: web
    name: chatterbox
    env: node
    plan: free
    buildCommand: >
      echo "DATABASE_URL: $DATABASE_URL" && 
      echo "Database environment variables:" && 
      env | grep -E "PG|DATABASE" && 
      npm install && 
      npm run build && 
      npm run db:push
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: chatterbox-db
          property: connectionString
      - key: PGHOST
        fromDatabase:
          name: chatterbox-db
          property: host
      - key: PGPORT
        fromDatabase:
          name: chatterbox-db
          property: port
      - key: PGUSER
        fromDatabase:
          name: chatterbox-db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: chatterbox-db
          property: password
      - key: PGDATABASE
        fromDatabase:
          name: chatterbox-db
          property: database

databases:
  - name: chatterbox-db
    plan: free
    databaseName: chatterbox
    ipAllowList: []