services:
  - type: web
    name: chatterbox
    env: node
    plan: free
    buildCommand: npm install && npm run build && npm run db:push
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: chatterbox-db
          property: connectionString

databases:
  - name: chatterbox-db
    plan: free
    databaseName: chatterbox
    ipAllowList: []